# -*- coding: utf-8 -*-
"""group_ACCL_Visualisation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpaYqw47wFJDADnzm_DeN_IzRNVyaEmL
"""

# Import relevant libraries
import pandas as pd
import csv
import matplotlib.pyplot as plt
import datetime
import numpy as np

array = pd.read_csv('temperatures_over_time.csv')

print(f"Columns: {array.columns}")

X, y = array[array.columns[0]], array[[array.columns[1], array.columns[2], array.columns[3], array.columns[4], array.columns[5], array.columns[6], array.columns[7], array.columns[8], array.columns[9],  array.columns[10]]]

import pandas as pd
import matplotlib.pyplot as plt

Temperature = [' y[0]', ' y[1]', ' y[2]', ' y[3]', ' y[4]', ' y[5]',
       ' y[6]', ' y[7]', ' y[8]', ' y[9]']

def plot_csv(temperatures_over_time, Time, Temperature):
    # Read CSV file
    df = pd.read_csv(temperatures_over_time)

    print(df.head())

    # Plot the data
    plt.figure(figsize=(10, 6))
    plt.plot(df[Time], df[Temperature], marker='o', linestyle='-')

    # Labels and title
    plt.xlabel('Time')
    plt.ylabel('Temperature')
    plt.title('Temperature vs Time')
    plt.xlim(0,12)
    plt.ylim(250,320)
    plt.grid(True)
    plt.grid(False)
    plt.legend(Temperature)



    # Show plot
    plt.show()

# Example usage
# plot_csv('temperatures_over_time.csv', 'Time', 'Temperature')

plot_csv("temperatures_over_time.csv", " time", Temperature)